package com.siar.risk.model;

public enum RiskAlertType {
    HIGH_RISK_EVALUATION,
    MEDIUM_RISK_EVALUATION,
    PEP_HIGH_RISK_DETECTED,
    ENHANCED_DD_REQUIRED,
    MANUAL_OVERRIDE_APPLIED,
    RISK_LEVEL_ESCALATION,
    SUPERVISOR_APPROVAL_REQUIRED,
    PERIODIC_REVIEW_DUE,
    CONFIGURATION_CHANGED
}
