export const API_ENDPOINTS = {
  auth: {
    login: "/api/auth/login",
    logout: "/api/auth/logout",
    refresh: "/api/auth/refresh",
    me: "/api/auth/me",
  },
  dossiers: {
    list: "/api/dossiers",
    create: "/api/dossiers",
    detail: (id: string) => `/api/dossiers/${id}`,
    update: (id: string) => `/api/dossiers/${id}`,
    delete: (id: string) => `/api/dossiers/${id}`,
    approve: (id: string) => `/api/dossiers/${id}/approve`,
    history: (id: string) => `/api/dossiers/${id}/history`,
  },
  screening: {
    execute: "/api/screening/execute",
    list: "/api/screening",
    detail: (id: string) => `/api/screening/${id}`,
    results: (id: string) => `/api/screening/${id}/results`,
    decide: (id: string) => `/api/screening/${id}/decision`,
    history: "/api/screening/history",
  },
  pep: {
    list: "/api/pep",
    create: "/api/pep",
    detail: (id: string) => `/api/pep/${id}`,
    update: (id: string) => `/api/pep/${id}`,
    history: (id: string) => `/api/pep/${id}/history`,
    riskImpact: (id: string) => `/api/pep/${id}/risk-impact`,
  },
  documents: {
    list: "/api/documents",
    upload: "/api/documents/upload",
    detail: (id: string) => `/api/documents/${id}`,
    approve: (id: string) => `/api/documents/${id}/approve`,
    reject: (id: string) => `/api/documents/${id}/reject`,
    download: (id: string) => `/api/documents/${id}/download`,
    alerts: "/api/documents/alerts",
  },
  alerts: {
    list: "/api/alerts",
    create: "/api/alerts",
    detail: (id: string) => `/api/alerts/${id}`,
    track: (id: string) => `/api/alerts/${id}/tracking`,
    close: (id: string) => `/api/alerts/${id}/close`,
    summary: "/api/alerts/summary",
  },
  audit: {
    logs: "/api/audit/logs",
    detail: (id: string) => `/api/audit/logs/${id}`,
    export: "/api/audit/export",
    regulatorView: "/api/audit/regulator",
  },
  risk: {
    evaluate: "/api/risk/evaluate",
    detail: (id: string) => `/api/risk/${id}`,
    override: (id: string) => `/api/risk/${id}/override`,
    history: (id: string) => `/api/risk/${id}/history`,
  },
} as const
