export const PERMISSIONS = {
  // Dossier permissions
  DOSSIER_CREATE: "dossier.create",
  DOSSIER_READ: "dossier.read",
  DOSSIER_UPDATE: "dossier.update",
  DOSSIER_DELETE: "dossier.delete",
  DOSSIER_APPROVE: "dossier.approve",

  // Screening permissions
  SCREENING_EXECUTE: "screening.execute",
  SCREENING_READ: "screening.read",
  SCREENING_DECIDE: "screening.decide",

  // PEP permissions
  PEP_CREATE: "pep.create",
  PEP_READ: "pep.read",
  PEP_UPDATE: "pep.update",
  PEP_APPROVE: "pep.approve",

  // Document permissions
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_READ: "document.read",
  DOCUMENT_APPROVE: "document.approve",
  DOCUMENT_DELETE: "document.delete",

  // Alert permissions
  ALERT_CREATE: "alert.create",
  ALERT_READ: "alert.read",
  ALERT_UPDATE: "alert.update",
  ALERT_CLOSE: "alert.close",

  // Audit permissions
  AUDIT_READ: "audit.read",
  AUDIT_EXPORT: "audit.export",
  AUDIT_REGULATOR_VIEW: "audit.regulator_view",

  // Risk permissions
  RISK_EVALUATE: "risk.evaluate",
  RISK_OVERRIDE: "risk.override",
  RISK_READ: "risk.read",
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export type RoleType =
  | "OFICIAL_CUMPLIMIENTO"
  | "USUARIO_RRHH"
  | "USUARIO_COMERCIAL"
  | "CONSULTOR"
  | "AUDITOR_INTERNO"
  | "REGULADOR_SUDEASEG"

export const ROLE_PERMISSIONS: Record<RoleType, Permission[]> = {
  OFICIAL_CUMPLIMIENTO: [
    PERMISSIONS.DOSSIER_CREATE,
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.DOSSIER_UPDATE,
    PERMISSIONS.DOSSIER_APPROVE,
    PERMISSIONS.SCREENING_EXECUTE,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.SCREENING_DECIDE,
    PERMISSIONS.PEP_CREATE,
    PERMISSIONS.PEP_READ,
    PERMISSIONS.PEP_UPDATE,
    PERMISSIONS.PEP_APPROVE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_APPROVE,
    PERMISSIONS.ALERT_CREATE,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.ALERT_UPDATE,
    PERMISSIONS.ALERT_CLOSE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.RISK_EVALUATE,
    PERMISSIONS.RISK_OVERRIDE,
    PERMISSIONS.RISK_READ,
  ],
  USUARIO_RRHH: [
    PERMISSIONS.DOSSIER_CREATE,
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.ALERT_READ,
  ],
  USUARIO_COMERCIAL: [
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.ALERT_READ,
  ],
  CONSULTOR: [
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.PEP_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.RISK_READ,
  ],
  AUDITOR_INTERNO: [
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.PEP_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.RISK_READ,
  ],
  REGULADOR_SUDEASEG: [
    PERMISSIONS.DOSSIER_READ,
    PERMISSIONS.SCREENING_READ,
    PERMISSIONS.PEP_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AUDIT_REGULATOR_VIEW,
    PERMISSIONS.RISK_READ,
  ],
}
